### ISSUE TITLE
I simply added it and it crashed

### ISSUE THREAD

**Issue by ak1dd** [dhelmr/ulauncher-duckduckgo-bangs#1]
I have to remove it as it crashes whenever it is added and active.

**Comment by dhelmr** [comment]
Hi, could you give more specific information about your operating system and ulauncher version? Is there any error output when you start ulauncher in a terminal by typing `ulauncher` and activate the extension? Thank you for testing the extension by any means :)

**Comment by DiscreteLoner** [comment]
I have the same problem. My

**Comment by sangsongthong-hexterika** [comment]
I had the same problem. My OS is Ubuntu 18.04 LTS. Ulauncher version 5.4.0.

Here is the error output from terminal after typing `ulauncher`

`/usr/lib/python3/dist-packages/ulauncher/main.py:8: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk`

**Comment by dhelmr** [comment]
Hi, thank you for testing. It seems that it is not working because the extension needs python 3.7, but ubuntu 18.04 ships version 3.6. I will look into it the next days and update when python 3.6 will be supported.

**Comment by dhelmr** [comment]
I

**Comment by dhelmr** [comment]
It should work now for Ubuntu 18.04. You can update the extension directly in ulauncher and afterwards reload the extension list.

**Comment by sangsongthong-hexterika** [comment]
Thanks.
