### ISSUE TITLE
The README leaves it unclear how one can search using DuckDuckGo itself/directly

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [dhelmr/ulauncher-duckduckgo-bangs#2]
Sometimes I don't want to, e.g., search with Google via `! g` or search Wikipedia via `! w`. [A separate extension](https://github.com/mikebarkmin/ulauncher-duckduckgo) allows one to search DuckDuckGo directly but surely it would be good were your extension to allow that. Perhaps it does. But if it does then the function seems undocumented!

**Comment by dhelmr** [comment]
Hi, thank you for your suggestion. You can use the bang for duckduckgo itself, which is `ddg`. However, there won't be search recommendations for it. I think this is out of scope for this extension.

I modified the README a bit, and hope it is now more clear what the extension does.

**Comment by LinuxOnTheDesktop** [comment]
Right. Thank you. Let me suggest though an improvement to the new text that you have in the README. I suggest that you change

> You can also access the DuckDuckGo search with this extension, by using the bang `! ddg.`

to

> You can use DuckDuckGo itself by using the bang `! ddg.`
